In [6]:
#building lists
fam_height=[1.75, 1.66, 1.3]
print(fam_height)

[1.75, 1.66, 1.3]


In [26]:
#lists of lists
fam_height2= [["han", 1.75],
          ["rob", 1.66],
          ["lu", 1.3]]

print(fam_height2)
print(type(fam_height2))

[['han', 1.75], ['rob', 1.66], ['lu', 1.3]]
<class 'list'>


In [15]:
#access list info
fam_height2[0]

['han', 1.75]

In [14]:
fam_height2[-1]

['lu', 1.3]

In [16]:
fam_height2[0:2]

[['han', 1.75], ['rob', 1.66]]

In [17]:
fam_height2[:2]

[['han', 1.75], ['rob', 1.66]]

In [19]:
fam_height2[:]

[['han', 1.75], ['rob', 1.66], ['lu', 1.3]]

In [23]:
fam_height2[0][1]

1.75

In [27]:
fam_height2[-1][-1] = 1.35
fam_height2

[['han', 1.75], ['rob', 1.66], ['lu', 1.35]]

In [29]:
fam_height2 + [["mom", 1.6]]

[['han', 1.75], ['rob', 1.66], ['lu', 1.35], ['mom', 1.6]]

In [39]:
tallest= max(fam_height)
tallest_round=round(tallest, 1)
print(tallest, tallest_round)

1.75 1.8


In [40]:
#playing with lists
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]
full= first + second
print(full)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [41]:
full_sorted= sorted(full, reverse=True)
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [55]:
#Methods
#methods are functions that belong to objects
#call method using dot notation
fam_height2= ["han", 1.75,
          "rob", 1.66,
          "lu", 1.3]
fam_height2.index("rob")

2

In [56]:
fam_height2.count("han")

1

In [62]:
sister = "han"
sister= sister.replace("n", "nnah")

In [69]:
fam_height2.append(sister)
print(fam_height2)

['han', 1.75, 'rob', 1.66, 'lu', 1.3, 'hannah']


In [70]:
fam_height2.append(1.77)

In [71]:
print(fam_height2)

['han', 1.75, 'rob', 1.66, 'lu', 1.3, 'hannah', 1.77]


In [72]:
#using and importing packages
import numpy as np

In [82]:
#numpy arrays contains only 1 type of object
fam_height=np.array(fam_height)

In [78]:
fam_weight= np.array([65,67,90])
fam_weight

array([65, 67, 90])

In [84]:
bmi=fam_weight/fam_height**2
bmi

array([ 21.2244898 ,  24.31412397,  53.25443787])

In [88]:
#using booleans on arrays
bmi > 23

array([False,  True,  True], dtype=bool)

In [87]:
bmi[bmi>23]

array([ 24.31412397,  53.25443787])

In [94]:
#2D numpy array
np_2d= np.array([fam_height,fam_weight])
print(np_2d)

[[  1.75   1.66   1.3 ]
 [ 65.    67.    90.  ]]


In [95]:
np_2d.shape


(2, 3)

In [97]:
#subsetting
np_2d[0][2]

1.3

In [98]:
np_2d[0,2]

1.3

In [99]:
np_2d[:, 2]

array([  1.3,  90. ])

In [104]:
#generate summaraizing statistics to look at data

#create random numbers for height and weight of a city
height= np.round(np.random.normal(1.75, .2, 5000), 2) #1.75 is mean, .2 is stdev, 5000 is number of samples)
weight= np.round(np.random.normal(60.32, 15, 5000), 2)
np_city= np.column_stack((height, weight))
print(np_city)

[[  1.72  83.33]
 [  1.72  66.88]
 [  2.05  86.94]
 ..., 
 [  1.81  73.22]
 [  2.13  63.02]
 [  1.5   62.84]]


In [114]:
mean_height= np.mean(np_city[:,0])
median_weight= np.median(np_city[:,1])

print("average height is", str(mean_height),"and the median wieght is", str(median_weight)) 

average height is 1.747666 and the median wieght is 60.51


In [120]:
stddev = np.std(np_city[:, 0])
corr= np.corrcoef(np_city[:,0], np_city[:,1])
print("Standard Deviation: " + str(stddev) + "and correlation: " + str(corr))

Standard Deviation: 0.200546384769and correlation: [[ 1.         0.0242995]
 [ 0.0242995  1.       ]]
